name: Build

on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build -x publish
