name: Create-Swift-Package

on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Create Swift Package
        run: ./gradlew createSwiftPackage
